trigger: none

pool:
  name: 'local-pool'

variables:
  imageName: labazizlab/pyflash
  dockerUserName: $(DOCKER_USERNAME)
  dockerPassword: $(DOCKER_PASSWORD)
stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      displayName: 'Build Docker Image'
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build Docker Image'
          inputs:
            containerRegistry: 'dockerhub-connection'
            repository: $(imageName)
            command: buildAndPush
            dockerfile: pro/Dockerfile
            buildContext: pro
            tags: build-$(Build.BuildId)

        - script: echo "##vso[task.setvariable variable=buildTag;isOutput=true]build-$(Build.BuildId)"
          name: SetTag  
          displayName: 'Set build tag as output'
- stage: UpdateYAML
  displayName: 'Update K8s YAML and Push'
  dependsOn: BuildAndPush
  jobs:
  - job: UpdateYAML
    displayName: 'Update and Push YAML'
    variables:
      tag: $[ dependencies.BuildAndPush.outputs['BuildImage.SetTag.buildTag'] ]
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        echo "Updating Kubernetes deployment YAML"
        sed -i "s#\(labazizlab/pyflash:\).*#\1${tag}#g" ./k3s/deploy-py.yaml
 - task: CmdLine@2
   displayName: 'Push updated YAML to GitHub'
    inputs:
      script: |
        git config --global user.email "20202016@fbsu.edu.sa"
        git config --global user.name "$(GITHUB_USERNAME)"
        git add .
        git commit -m "updated deployment"
        git pull origin main
        git push https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/labazizlab/nginx-app.git HEAD:main
      failOnStderr: false
    env:
      GITHUB_USERNAME: $(GITHUB_USERNAME)
      GITHUB_TOKEN: $(GITHUB_TOKEN)
