apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyflask-deploy
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyflask
  template:
    metadata:
      labels:
        app: pyflask
    spec:
      containers:
        - name: pyflask
          image: labazizlab/pyflash:build-30
          ports:
            - containerPort: 5000
