apiVersion: v1
kind: Service
metadata:
  name: pyflask-svc
  namespace: webserver
spec:
  selector:
    app: pyflask
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
