name: run manual

on:
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker tag
      id: set_tag
      run: echo "TAG=build-${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t labazizlab/pyflash:${{ env.TAG }} ./code

    - name: Push Docker image
      run: |
        docker push labazizlab/pyflash:${{ env.TAG }}

    - name: Output image tag
      run: echo "Image tag is ${{ env.TAG }}"
