name: run manual

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag
        id: set_tag
        run: echo "TAG=build-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t labazizlab/pyflash:${{ env.TAG }} ./pro

      - name: Push Docker image
        run: docker push labazizlab/pyflash:${{ env.TAG }}

      - name: Output image tag
        run: echo "Image tag is ${{ env.TAG }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Update deployment YAML with new build ID
        run: |
          sed -i "s/image: labazizlab\/pyflash:.*/image: labazizlab\/pyflash:${{ env.TAG }}/" ./k3s/deploy-py.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./k3s/deploy-py.yaml
          git commit -m "Update deployment to use image ${{ env.TAG }}"
          git push
